### ISSUE TITLE
Question: Using entity browser

### ISSUE THREAD

**Issue by cyberquarks** [JetBrains/xodus-entity-browser#28]
I have some few questions:

1. What's the purpose of Database State ON/OFF in the browser? 
2. Can the Xodus Entity Browser manage production database? I understand that you can't open the same environment that is locked by an application, so how can this entity browser work at all? 
3. Does it mean that it manages database that are either copied or synced from a remote server?

**Comment by lehvolk** [comment]
At the moment Entity Browser is used in few ways:
1. standalone tool to investigate cases in databases or for development purposes
2. embed Entity Browser into working application

In second case target application already has one or more opened environments. This environments could be served to Entity Browser. Unfortunately Entity Browser has no public build artifacts for both backend and frontend. This could be improved. You could build them yourself as a temporary solution.

> What's the purpose of Database State ON/OFF in the browser?

It's for 1 use-case when entity browser used as a standalone tool. You could add some database locally and then release it for other application switching to OFF state.

> Can the Xodus Entity Browser manage production database? I understand that you can't open the same environment that is locked by an application, so how can this entity browser work at all?

Yes, Entity Browser could manage production. Actually you can open database from working application but in readonly mode. We use Entity Browser in few applications in production in the embedded way in both readonly and read-write mode. We use RW mode very carefully because our applications using https://github.com/JetBrains/xodus-dnq as a top level framework. Entity Browser uses low level api and as a result all cascades/constraints checks are not checked.

> Does it mean that it manages database that are either copied or synced from a remote server?

You could do it this way too.
